theme: jekyll-theme-minimal
title: ["Jennifer L. Cross"]
description: ["Roboticist. Educator. Designer."]

show_downloads: [false]
google_analytics_key: UA-109769074-1
google_analytics: UA-109769074-1

# Collections
collections:
    courses:
        output: true
    projects:
        output: true

# Default layouts
defaults:
    - scope:
          path: ""
          type: "projects"
      values:
          layout: "project"
    - scope:
          path: ""
          type: "courses"
      values:
          layout: "course"
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
    - scope:
          path: ""
      values:
          layout: "default"
